spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USER_NAME}
    password: ${MYSQL_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: validate

  jwt:
    secret:
      key: ${JWT_SECRET_KEY}
