spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USER_NAME}
    password: ${MYSQL_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: validate

  jwt:
    admin:
      secret: ${ADMIN_JWT_SECRET}
      access-token-expiry: 1800000
    creator:
      secret: ${CREATOR_JWT_SECRET}
      access-token-expiry: 1800000
